### 0. 데이터로딩

In [1]:
import joblib
def get_nouns(text):
    return 1
with open('tdm.pkl', 'rb') as f:
    data = joblib.load(f)
    print(data.keys())
    locals().update(data)
    del data

dict_keys(['cv', 'tfidf', 'tdm_cv', 'tdm_tfidf'])


In [2]:
import pandas as pd
df = pd.read_csv('review_full.csv')
df.head()

지역          식당이름            리뷰일          리뷰어ID   평점  \
0  서울  서울24시감자탕 서현점    2020년 9월 4일       Go807705  5.0   
1  서울  서울24시감자탕 서현점   2020년 3월 26일         OERWJ2  4.0   
2  서울  서울24시감자탕 서현점   2020년 2월 25일         jgp982  5.0   
3  서울  서울24시감자탕 서현점   2020년 2월 15일  Getaway807239  4.0   
4  서울  서울24시감자탕 서현점  2019년 11월 22일    kingkong_hi  5.0   

                                               리뷰텍스트  
0  여러 감자탕 가게를 다녀봤는데 손에 꼽힐 정도로 괜찮은 식당임. 뼈에 붙은 살도 신...  
1  고기가 질기지 않고 가격대도 괜찮아서 점심에 부담없이 찾아가기 좋다. 성남살면서 자...  
2  어른들은 주로 뼈해장국 아이들은 안 매운 삼계탕. 언제나 든든하고 후회없는 선택입니...  
3  분당내 다른체인점임낳은곳으로 감자탕 맛집이에요 가격도 비싸지 않고요 고기도 실합니다...  
4  맛있어서 자주 갑니다. 매장에서는 감자탕 먹고 포장은 뼈해장국~ 뼈해장국 밥 빼고 ...

### 1. 유사도 계산

In [3]:
from sklearn.metrics.pairwise import euclidean_distances, cosine_similarity

In [4]:
euclidean_distances(tdm_cv[0], tdm_cv[1])

array([[3.74165739]])

In [5]:
euclidean_distances(tdm_cv[0], tdm_cv[110])

array([[7.87400787]])

In [6]:
df.loc[0, '리뷰텍스트']

'여러 감자탕 가게를 다녀봤는데 손에 꼽힐 정도로 괜찮은 식당임. 뼈에 붙은 살도 신선하면서도 많으며 함께 나오는 시래기도 무척 싱싱함. 항아리에 담겨있는 김치는 겉절이 느낌이 날 정도로 자주 담는 것 같음.'

In [7]:
df.loc[1, '리뷰텍스트']

'고기가 질기지 않고 가격대도 괜찮아서 점심에 부담없이 찾아가기 좋다. 성남살면서 자주 들르는집. 뭐든지 항상 평균이상은 해주는 감자탕집'

In [8]:
df.loc[110, '리뷰텍스트']

"서울의 Pierre Gagnaire는 최근 저의 서울 맛집 여행에서 가장 돋보였던 식사였어요. 식사 공간이 화려하고 도시 조망이 멋지고 서비스도 근사해요. 코스마다 작은 접시가 시리즈로 나오는데 예를 들면 주요리로는 다섯 가지 다른 음식이 나와요. 저희는 4가지 코스로 나오는 L'Espirit 메뉴를 골랐는데 양도 적당하고 맛을 정말 음미할 수 있었어요! 메인 요리는 제가 지금껏 맛본 최고의 요리 중 하나였어요! 바닷가재가 나왔는데 망고로 아름답게 장식돼 있었고 특히 바닷가재 비스크는 상상 이상으로 최고 맛있어요! 물론 Pierre Gagnaire에서 식사하는 게 무척 비싸긴 하지만 정말 가볼 만해요. 아주 오랫동안 기억에 남을 한 끼를 먹는 거니까요! Pierre Gagnaire에 대한 제 총평은 아래 링크를 참고하세요.: http://foodmab.blogspot.com.au/2013/03/pierre-gagnaire-seoul-6-november-2012.html"

In [9]:
dist = euclidean_distances(tdm_cv[0], tdm_cv[1:])

In [10]:
import numpy as np
np.argmin(dist) + 1

14347

In [11]:
df.loc[0, '리뷰텍스트']

'여러 감자탕 가게를 다녀봤는데 손에 꼽힐 정도로 괜찮은 식당임. 뼈에 붙은 살도 신선하면서도 많으며 함께 나오는 시래기도 무척 싱싱함. 항아리에 담겨있는 김치는 겉절이 느낌이 날 정도로 자주 담는 것 같음.'

In [12]:
df.loc[np.argmin(dist) + 1, '리뷰텍스트']

'40분의 기다림..그닥 특별함이라고 하면 순대볶음에 깻잎을 올려준다는 정도? 그냥 지나가다가 사먹을 정도라고 본다.'

In [13]:
cosine_similarity(tdm_cv[0], tdm_cv[1])

array([[0.12598816]])

In [14]:
cosine_similarity(tdm_cv[0], tdm_cv[110])

array([[0.]])

In [15]:
sim = cosine_similarity(tdm_cv[0], tdm_cv[1:])
np.argmax(sim) + 1

9643

In [16]:
df.loc[0, '리뷰텍스트']

'여러 감자탕 가게를 다녀봤는데 손에 꼽힐 정도로 괜찮은 식당임. 뼈에 붙은 살도 신선하면서도 많으며 함께 나오는 시래기도 무척 싱싱함. 항아리에 담겨있는 김치는 겉절이 느낌이 날 정도로 자주 담는 것 같음.'

In [17]:
df.loc[np.argmax(sim) + 1, '리뷰텍스트']

'맛있게 먹긴했지만 이렇게까지 유명해질 정도는 솔직히 아니다. 마케팅과 pr 홍보의 힘은 정말 대단하다 싶다'

### 2. 군집화

In [18]:
from sklearn.cluster import SpectralClustering
np.random.seed(123)
cl = SpectralClustering(n_clusters = 4)

In [19]:
labels = cl.fit_predict(tdm_cv[:100])
labels

array([2, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 3, 0, 0, 3, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
from operator import itemgetter
words = cv.get_feature_names()
freq_words = []

for i in range(4):
    count = tdm_cv[labels==i, :].sum(axis=0)
    ws = [w for w, n in sorted(zip(words, count.flat), 
                               key=itemgetter(1), reverse=True)][:10]
    freq_words.append(ws)

In [21]:
pd.DataFrame(freq_words)

0    1    2   3    4     5   6   7   8    9
0  감자탕   고기   식사  음식   가격    국물  방문  생각  사람  서비스
1   음식   코스   느낌  메뉴  웨이터  레스토랑  생각  시간  요리   인상
2   정도   김치  감자탕  가게  깍두기    느낌  도착  동안  맛집   메뉴
3   포장  해장국  감자탕  제일   인분    건강  고려  국물  그중   근처